import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import style from "@/styles/Home.module.css";
import Link from "next/link";
import Header from "@/pages/components/header";
import Content from "@/pages/components/content";
import useSWR from 'swr';


export default function Home() {
  let title = "のぶひで";

  const { data, error } = useSWR("/api/message");

  if (error) return <div>failed to load</div>;
  if (!data) return <div>loading...</div>;

  return (
    <>
      <Content>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <p>これはHOMEページです</p>
          <Header title="HOME" />
          <p>{data?.message}</p>
          <div>
            <Link href="/about">Link About</Link>
          </div>
        </main>
      </Content>
    </>
  );
}
